export const FETCH_PICTURE_OF_A_DAY = "FETCH_PICTURE_OF_A_DAY";
export const FETCH_EPIC = "FETCH_EPIC";
export const FETCH_MARS_WEATHER = "FETCH_MARS_WEATHER";
export const FETCH_MARS_CURIOSITY_PICTURES = "FETCH_MARS_CURIOSITY_PICTURES";
export const FETCH_MARS_OPPORTUNITY_PICTURES = "FETCH_MARS_OPPORTUNITY_PICTURES";
export const FETCH_MARS_SPIRIT_PICTURES = "FETCH_MARS_SPIRIT_PICTURES";
export const FETCH_SEARCH_PICTURES = "FETCH_SEARCH_PICTURES";
export const FETCH_MORE_SEARCH_PICTURES = "FETCH_MORE_SEARCH_PICTURES";